os:
  - linux
  - osx

language: dart
dart:
  - "dev/raw/latest"
# "dev/release/1.16.0-dev.3.0"
addons:
  chrome: stable

env:
  - BOT=main
  - BOT=test_ddc
  - BOT=test_dart2js
  - BOT=flutter_sdk_tests

script: ./tool/travis.sh

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.pub-cache
