language: minimal
addons:
  chrome: stable
os:
  - linux
  - osx
  # TODO(dantup): Skip on windows until we understand/fix Flutter crashing
  # with "failed to delete build/assets: file is locked by another process".
  #- windows

matrix:
  fast_finish: true
    
  # Allow windows bots to fail until we can make the windows tests less flaky.
  # https://github.com/flutter/devtools/issues/963
  allow_failures:
    - os: windows
    - os: osx

env:
  global:
    - CHANNEL=dev
  jobs:
    - BOT=main                CHANNEL=dev
    - BOT=main                CHANNEL=master
    - BOT=packages
    - BOT=test_ddc            PLATFORM=vm
    - BOT=test_ddc            PLATFORM=chrome
    - BOT=test_dart2js        PLATFORM=vm
    - BOT=test_dart2js        PLATFORM=chrome
    - BOT=integration_ddc
    - BOT=integration_dart2js

script: ./tool/travis.sh

# Specifying master here means that we don't run two builds for each pull request
# made from within the DevTools repo, however it complicates running builds on
# forks without opening PRs.
# See https://github.com/flutter/devtools/pull/398
# branches:
#   only: [master]

cache:
 directories:
 - $HOME/.pub-cache # macOS / Linux
 - $APPDATA/Roaming/Pub/Cache # Windows
 - packages/devtools_app/.dart_tool/build
