name: devtools
description: Performance tools for Flutter.
version: 0.0.1
homepage: https://github.com/flutter/devtools

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  intl: ^0.15.0
  logging: ^0.11.0
  meta: ^1.1.0
  path: ^1.6.0
  vm_service_lib: ^0.3.9+1

dev_dependencies:
  build_runner: '>=0.8.10 <0.11.0'
  build_web_compilers: any
  test: ^1.0.0
  webdev: 0.2.4+1
  webkit_inspection_protocol: ^0.3.6
