# An empty analysis options file - we don't want the default repo analysis options here.

analyzer:
  errors:
    dead_code: ignore
    deprecated_member_use_from_same_package: ignore
    missing_return: ignore
    undefined_shown_name: ignore
    unused_element: ignore
    unused_field: ignore
    unused_import: ignore
    unused_local_variable: ignore
    unused_shown_name: ignore
