name: devtools

on:
  pull_request:
  push:
    branches:
      - master

env:
  CHANNEL: dev
  BOT: main

jobs:
  build:
    name: "todo build job name"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # - name: Install Dart
      #   env:
      #     DART_VERSION: ${{ matrix.dart-version }}
      #   run: |
      #     ./.github/install-dart.sh
      #     echo "::add-path::`pwd`/dart-sdk/bin"
      #     echo "::add-path::$HOME/.pub-cache/bin"

      - name: Run CI script
        #working-directory: ${{ matrix.bot }}
        # TODO: Rename this script.
        run: ./tool/travis.sh
